language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to run tests
install:
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py install
  - travis_retry pip install -U numpy

script:
  - nosetests -v --with-coverage --cover-package=proxalgs

after_success:
  - coveralls
